### ISSUE TITLE
doesn't work on yosemite

### ISSUE THREAD

**Issue by edoardoc** [michaelvillar/timer-app#1]
I am still on yosemite

![screen shot 2016-04-06 at 17 18 58](https://cloud.githubusercontent.com/assets/368717/14319910/b6aaefd2-fc1b-11e5-9dd1-c0c7f43669b8.png)

**Comment by scottperezfox** [comment]
+1 — Considering it's only one release back, and essentially the same, I'd really like to see a version that works on Yosemite.

**Comment by quver** [comment]
This causes a bit mess in one class with fonts but it is possible. I try to prepare PR tomorrow.

**Comment by michaelvillar** [comment]
Anyone wants to try this build that should work on Yosemite?
[Timer.app.zip](https://github.com/michaelvillar/timer-app/files/269756/Timer.app.zip)

**Comment by michaelvillar** [comment]
Actually, just published 1.1.0
https://github.com/michaelvillar/timer-app/releases/tag/1.1.0
