### ISSUE TITLE
Distribute by homebrew

### ISSUE THREAD

**Issue by bensleveritt** [michaelvillar/timer-app#10]
Great app. Would love to see a homebrew cask install option, that'd be cool.

Might even get round to it myself.

**Comment by michaelvillar** [comment]
Feel free :)

**Comment by pasqualesalza** [comment]
Hi,
I just submitted the cask to the repository. You'll find it with the name: michaelvillar-timer..

Thank you for your effort!

**Comment by shpakovski** [comment]
Hi guys, thanks for your efforts. The command line `brew cask install michaelvillar-timer` works like a charm, feel free to close the Issue!

**Comment by michaelvillar** [comment]
Thanks guys.
