### ISSUE TITLE
Minimize / Hide the timer, Dark interface

### ISSUE THREAD

**Issue by Aayush9029** [michaelvillar/timer-app#100]
Would love a minimize button so it's not distracting anymore as it can be annoying at times.
Also it would be awesome if the center interface was also dark, maybe grey-ish. 

**That would be awesome**

If this is something you are not looking into adding, feel free to let me know I'm ready to fork!!

Great job BTW <3

**Comment by robinstewart** [comment]
@Aayush9029 Thanks for the feedback.

1. Hiding the timer — you can simply close the timer (red button) and it will continue to run in your dock. Click the dock icon to open the timer window again. So, it basically works as minimize. Whether this is the best UI is another question. If you want to pursue this please file a separate issue.

2. Dark mode with dark center — @aonez did some prototyping along these lines in #24 but no one did the design work to really make the dark center look great so we kept the white center. Yes, you're more than welcome to work on this and submit a pull request! I'm also happy to review your designs if you'd like feedback.
