### ISSUE TITLE
No red badge on Dock icon with remaining time on Big Sur

### ISSUE THREAD

**Issue by wojtekcz** [michaelvillar/timer-app#104]
I don't see red badge on Dock icon with remaining time on Big Sur.

**Screenshot:**
![image](https://user-images.githubusercontent.com/1236889/100583303-cd1e8e80-32ea-11eb-856f-ceebb408c866.png)

**Desktop:**
 - OS version: macOS Big Sur 11.0.1
 - Version: 1.5.5

**Comment by silomia** [comment]
It is working for me now, as expected, with the new Timer 1.6 on Big Sur 11.1.

**Comment by wojtekcz** [comment]
Timer 1.6 works for me too :-)

**Comment by karbassi** [comment]
Thanks @legissa and @wojtekcz for confirming. Closing this issue.
