### ISSUE TITLE
Option to stay on top

### ISSUE THREAD

**Issue by silomia** [michaelvillar/timer-app#110]
I would like an option to keep Timer on top of all windows. The badge on the Dock is fine but after some time, the countdown is refreshed every 10 or 15 seconds. Keeping the timer on top can be useful to get the timer always in sight.

**Comment by karbassi** [comment]
Already a feature.

![Screen Shot 2021-01-20 at 10 40 53 AM](https://user-images.githubusercontent.com/17738/105206428-fcdc5c80-5b0b-11eb-86dc-0a9b632e9961.png)
