### ISSUE TITLE
Timer is not counting down

### ISSUE THREAD

**Issue by qpwo** [michaelvillar/timer-app#114]
MacOS 11.1 2015 MBP timer doesn't go when you hit go. Stops after one second. Nothing in logs if you run binary from command line.

https://user-images.githubusercontent.com/10591373/107737530-972a5d00-6cd2-11eb-8fe2-4fcad5a98127.mov

**Comment by karbassi** [comment]
@qpwo that for the issue.

Can you press <kbd>spacebar</kbd> or <kbd>return</kbd> once it's paused to see if it start again?

Not stating that is the solution, but trying to see if it's related to the bug.

This also might be related to #95

**Comment by qpwo** [comment]
Spacebar and return do not work

**Comment by qpwo** [comment]
Mysteriously started working again
