### ISSUE TITLE
Make timer-app available via MacPorts

### ISSUE THREAD

**Issue by gabriellovate** [michaelvillar/timer-app#122]
**Is your feature request related to a problem? Please describe.**
Some users prefer to use MacPorts instead of Homebrew, thus it would be nice to be able to install the app via MacPorts.

**Describe the solution you'd like**
Make timer-app available on MacPorts.

**Describe alternatives you've considered**
The alternative for these people is to download the app directly from GitHub, but then the ability to manage the package is gone.

**Comment by karbassi** [comment]
@gabriellovate Thanks for the issue.

Anyone can add a PR to MacPorts. Submit a PR to the MacPorts repo. Instructions: https://guide.macports.org/chunked/project.contributing.html
