### ISSUE TITLE
Could it could the amount of times it reached 0? 

### ISSUE THREAD

**Issue by khofstadter** [michaelvillar/timer-app#124]
Hi! 

I don't have any issues with the app, it's pretty cool. Thanks for making it!

I restart it several times throughout the day, but I am not exactly sure how often. I could take note of how often I restart it in a file or a piece of paper, but... it would be cool to see a value incrementing on the GUI e.g. arabic, roman or some funky alien numbers :)

![1472161235_Untitled-pred](https://user-images.githubusercontent.com/290828/171865425-aff3c957-d563-4719-a7be-a28cca92f29e.gif)

Thanks! 

k

**Comment by karbassi** [comment]
Hello @khofstadter From the gif you posted, I think you may have the wrong github repo project.

**Comment by khofstadter** [comment]
He-he! Thanks. It's the right repo, I was kinda joking with the predator numbers. To clarify: 

![Screenshot_2022-06-03_at_22_28_31](https://user-images.githubusercontent.com/290828/171955859-ee424232-48c6-4b3b-88ed-43ca4edf1ff6.jpg)
