### ISSUE TITLE
[DELETE]

### ISSUE THREAD

**Issue by gsheni** [michaelvillar/timer-app#13]
N/A

**Comment by efimovdk** [comment]
I support the question above. I like the current solution: simply typing minutes from keyboard. This is not even a textfield. So I don't need to activate it by clicking on it, then type in minutes. Thus, I can set up timer without trackpad and operate it purely by keyboard. This is indeed great approach. As to the question. Let's control seconds by holding shift key? You want to set minutes - you just type number. You want to seconds seconds as well - hold shift and type number. Looks like a solution to me. Anyway thanks for the work. BTW, I adore the notification sound!

**Comment by efimovdk** [comment]
@michaelvillar Any thoughts on this?
