### ISSUE TITLE
[Feature request] Is it possible to save a timer?

### ISSUE THREAD

**Issue by gudh** [michaelvillar/timer-app#16]
First of all, great app! Clean design, nice to use, thank you!

Personally, I use 25min and 50min timer a lot, I wonder if it's possible to save a timer so I don't need to set it up for 50min every time I use it, instead, just a simple click.

**Comment by michaelvillar** [comment]
One feature that might interest you is that the keyboard is supported. Just
type 25 or 50 and you'll get your timer.

**Comment by gudh** [comment]
@michaelvillar wow~ thanks! This helps a lot
