### ISSUE TITLE
Update mac osx doc icon with actual time

### ISSUE THREAD

**Issue by akarki15** [michaelvillar/timer-app#17]
It would be awesome if the app also updated the dock icon with actual time left so I wouldn't have to click the icon to know how much time has passed.

**Comment by DummybugStudios** [comment]
What if you have multiple timers on? Which one would show up?

**Comment by akarki15** [comment]
i didn't even know you could have multiple timers! when there are multiple timers, you could show an option on each timer that would designate it as the one which would show up in the doc icon.

**Comment by DummybugStudios** [comment]
Okay lovely I'll see if I can implement this? You may have to wait a little while as I'm backed up with exams and don't have a lot of time.

**Comment by DummybugStudios** [comment]
@akarki15 
My latest commit now adds a badge to the dock tile:
https://github.com/DummybugStudios/timer-app/commit/5cde4397817d9eb1d945a0dad1368189a44b5a1a
However, if you have multiple timers which one it will choose is still a little random so I won't be opening a pull request until I have sorted that out.
In the meantime - feel free to build that branch and enjoy the badge :)

**Comment by DummybugStudios** [comment]
@akarki15 I have opened a pull request for the badge.
You have to right click teh window and choose "show in dock" to show the timer in the dock.
