### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by aonez** [michaelvillar/timer-app#24]
I was just messing around with the code, to get started with #21, and since you've asked dark menu support, wouldn't it be gorgeous to have a dark skin as well?

Called "Skins" the ticket because this can be just a dark skin or a customisable skins enhancement. Just some raw ideas:

- Dark skin (automatic with dark menu)
- Customizable skins: get rid of the image sets or add some layer on top of them

Some quick samples:

![screen shot 2018-03-10 at 09 07 54](https://user-images.githubusercontent.com/480163/37239888-caf71032-2442-11e8-93a1-19568000b397.png)
![screen shot 2018-03-10 at 09 14 39](https://user-images.githubusercontent.com/480163/37239927-804a6056-2443-11e8-92c6-eec446b309d9.png)

**Comment by quantumgolem** [comment]
Would it be possible to upload higher-res screenshots?

I only think the text colors could use a little tweaking. I think red doesn't look as good on the dark background, and maybe the text in the center of the second screenshot could be lighter.

But these look very nice! Good job on them.

**Comment by aonez** [comment]
It was just a quick test, only modified the background. A lot more can be done :) No higher res screenshots since I don’t own a retina Mac...

**Comment by quantumgolem** [comment]
@aonez I just need to let you know if you don't already, this app looks absolutely _gorgeous_ on retina Macs. I'll try to modify it myself and see what I can come up with.

**Comment by aonez** [comment]
https://github.com/aonez/timer-app/commit/1dc2b6370f30c6100839cda2e543c7ed044a7263

Here's what I've changed. Changing the text color is easy too, and also changing the clock-focus images.

**Comment by karbassi** [comment]
Renamed this to "Dark Mode" since a dark mode would be a good fit for what this issue is asking for.
