### ISSUE TITLE
Add build instructions and release

### ISSUE THREAD

**Issue by karbassi** [michaelvillar/timer-app#31]
Hey @michaelvillar, I love this simple app. I use it daily.

Can you cut a new release with the recent changes?

Also, it would be nice to have build instructions somewhere. I used the following in terminal.

```sh
xcodebuild -quiet clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
```

Then the app is within `build/Release`.

**Comment by michaelvillar** [comment]
Added https://github.com/michaelvillar/timer-app/commit/c5d6fea87794d98443677f82a51c038160ce4838
