### ISSUE TITLE
Mojave Bug: Transparent "Watchface" in passive mode

### ISSUE THREAD

**Issue by BrandlMax** [michaelvillar/timer-app#40]
Hello guys, 
first of all... i love this app! Thank you!

I switched to Mojave on Monday, so I noticed this bug. As soon as the timer window is no longer active/focused, the "watchface" becomes transparent. But if I click on the timer window and make it to my active / current window, everything looks good again. Strange.

<img width="250" alt="bildschirmfoto 2018-09-27 um 11 38 20" src="https://user-images.githubusercontent.com/4717848/46137664-6739a680-c24a-11e8-8ee3-58b82ce6d093.png">

Thank you,
Max

**Comment by marbetschar** [comment]
Same here too. BTW: A dark mode for the timer in Mojave would be awesome ;)

**Comment by bartoszbak** [comment]
Facing the same issue.

**Comment by karbassi** [comment]
@robinstewart  thoughts on this fix?

**Comment by robinstewart** [comment]
Ok, I have a working fix for this. However, it will have merge conflicts with the Swift 5 update, so I will wait until that is merged in before I create a pull request.

Details: The clock face was an `NSImageView` which is automatically dimmed in macOS Mojave and later. I have not found any way to disable this behavior, so instead I just converted the clock face to a custom `NSView` that draws itself.

https://github.com/robinstewart/timer-app/tree/transparent-watchface

**Comment by karbassi** [comment]
@robinstewart I merged your fixes into #67 

Tested and it works well!
