### ISSUE TITLE
Tag and release 1.5.0

### ISSUE THREAD

**Issue by karbassi** [michaelvillar/timer-app#43]
Hey @michaelvillar,

Would it be possible to build a new release for the changes since 1.4?

https://github.com/michaelvillar/timer-app/compare/1.4...master

If you're super busy, I'm willing to join the project and do basic stuff like making releases, keeping a changelog, and testing.

**Comment by luckman212** [comment]
@karbassi I vote for this! Been hoping for a new Timer release for a while now.

**Comment by alper** [comment]
I'm very happy with the app and I'm noticing some minor bugs etc. that I hope may have been fixed in master. So eagerly awaiting somebody cutting another release.

**Comment by alper** [comment]
Never mind. I made a build for myself just now.

**Update:** Current master seems to be quite broken when built.

**Comment by luckman212** [comment]
@alper I don't see a fork in your repos, can you share your release somehow? It seems @michaelvillar isn't coming back to this anytime soon 😞

**Comment by alper** [comment]
@luckman212 As soon as I have time, I'll dive into this but for now I'm making do with the latest release on Github.

**Comment by karbassi** [comment]
Hey @alper @luckman212 @robinstewart, we do need a little help with a few issues before we can push 1.5.

See https://github.com/michaelvillar/timer-app/milestone/1

Any help would be appreciated!

**Comment by karbassi** [comment]
# 💥 Version 1.5.0 released! 💥

Thank you to @robinstewart for the help and thanks to @michaelvillar for a wonderful project!

**Comment by robinstewart** [comment]
And thanks to @karbassi for managing the release!
