### ISSUE TITLE
How about add stop watch function?

### ISSUE THREAD

**Issue by henryqhl** [michaelvillar/timer-app#46]
when timer is stopped, click timer (central circle) to start stop watch;
when stop watch started, click timer to tag a time, and print out the tag ticket from bottom of the app;
put a stop/reset button to the right bottom corner to stop (when stop watch running) or reset (when stop watch stoped).

**Comment by karbassi** [comment]
My vote is keeping this app simple. Maybe fork the app and create a stopwatch version?
