### ISSUE TITLE
Sound choice

### ISSUE THREAD

**Issue by michaelvillar** [michaelvillar/timer-app#49]
Hey,

Anyone wants to add the possibility to choose the sound of the alarm? (A menu or preference would be enough).
Someone (Ralph, not sure if you want your full name here) sent me sounds he created and it's pretty sweet.

[alert-sound1.zip](https://github.com/michaelvillar/timer-app/files/2705648/alert-sound.caf.zip)
[alert-sound2.zip](https://github.com/michaelvillar/timer-app/files/2706257/alert-sound.caf-1.zip)

**Comment by bensleveritt** [comment]
Could I also request a ticking sound when on? I use Timer for a pomodoro timer, and it's near perfect, but I kind of like some constant ticking noises (helps to make it clear I need to focus). Opt-in of course, might be a bit alarming for others

**Comment by silomia** [comment]
These sounds are an excellent addition. I find them somewhat better, less intrusive or irritative. The sounds are for different moods. I like them. Please consider adding them.

**Comment by karbassi** [comment]
PR welcome!

**Comment by shadow-2020** [comment]
Hello man, I like this App very much. But I got no sound when time was up. Could you please tell me what I can do to add the sounds? Thanks a lot.
