### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by marcuspoehls** [michaelvillar/timer-app#5]
Honestly, the timer app is great! Thanks for putting in the work Michael!

Do you have any plans or think it might be useful to add "time adjustment shortcuts" like just typing a number and the timer automatically sets its minutes?

**Comment by michaelvillar** [comment]
No big plan of the sort. Any specific use case?

**Comment by marcuspoehls** [comment]
I’m usually using the same time period all day to focus my work and would love to have a faster way to set the time by just typing like "25" instead of dragging the little triangle to "25".

Or a "reset" functionality to the default time would help as well.

**Comment by michaelvillar** [comment]
[edit]

Ok just did something about it: https://github.com/michaelvillar/timer-app/releases/tag/1.1.0

**Comment by marcuspoehls** [comment]
This is awesome! 

Thanks so much for listening to this request and the fast implementation! ❤️ 
Hope this feature is benefitial for others, too. Fits exactly my use case 👍

**Comment by michaelvillar** [comment]
Woot!
