### ISSUE TITLE
12-hour support

### ISSUE THREAD

**Issue by dixitk13** [michaelvillar/timer-app#54]
Can we have 12-hour mode with an AM/PM symbol? 

Perhaps a setting, which allows to toggle between 12hour/24hour mode

**Comment by karbassi** [comment]
@dixitk13 great idea. 

PR are welcome!

**Comment by robinstewart** [comment]
I actually already implemented this, using the setting in System Preferences to determine whether 24-hr or AM/PM is displayed.

You can use the feature now if you build the app yourself from source, but we are waiting for Michael to release a new pre-built version with the latest features.

**Comment by dixitk13** [comment]
I see the commit 8676e1c6de387ad7d666a54ee0bf5e1f3f1a2685 now which does this. Thanks a ton, @robinstewart. I can try building this, I see a makefile as well.

**Comment by karbassi** [comment]
@robinstewart I'm working on getting automatic builds setup via Travis or CircleCI. Hopefully I'll have a new build coming out very soon.

**Comment by karbassi** [comment]
Related to #57

**Comment by karbassi** [comment]
As @robinstewart said, it's already implemented.

For example, is I have `24-Hour Time` set in my "Language & Region", it shows as such:

![Screen Shot 2020-04-09 at 22 32 29](https://user-images.githubusercontent.com/17738/78959916-03847080-7ab2-11ea-8a34-51b9908f7429.png)

Here is `24-Hour Time` unchecked.

![Screen Shot 2020-04-09 at 10 32 41 PM](https://user-images.githubusercontent.com/17738/78959935-14cd7d00-7ab2-11ea-8815-ea2397fb32dc.png)
