### ISSUE TITLE
Reusing your assets for an elementary OS clone?

### ISSUE THREAD

**Issue by marbetschar** [michaelvillar/timer-app#58]
Hi Michael,

I switched recently to elementary OS and I really miss your awesome timer app. Have to admit I fell in love with it on macOS. That's why I just started cloning it: https://github.com/marbetschar/timer

Unfortunately I'm more of a programmer than a designer. And as I really like your design, I wanted to ask you if you're cool if I reuse [your assets](https://github.com/michaelvillar/timer-app/tree/master/Timer/Assets.xcassets) for a dedicated elementary OS clone, programmed in Vala?

To be fully transparent here, I also plan to release this Timer clone to the elementary OS AppCenter, a Pay-What-You-Want App Store. I'll probably publish it there with a suggested one-time price of 1 or 2 USD.

**Comment by michaelvillar** [comment]
Go for it! Would love to see what you end up making :)

**Comment by marbetschar** [comment]
Thank you very much!!

**Comment by marbetschar** [comment]
Will keep you posted!

**Comment by marbetschar** [comment]
@michaelvillar forgot to ask: Any chance you got the assets laying around somewhere in SVG format?

**Comment by michaelvillar** [comment]
Here's the Sketch file (unfortunately I think Sketch is a macOS software)
[timer-app.sketch.zip](https://github.com/michaelvillar/timer-app/files/4136244/timer-app.sketch.zip)

**Comment by marbetschar** [comment]
😍😍😍

Thank you!!!

**Comment by marbetschar** [comment]
As promised a quick update on the elementary clone: The first version is done and waits to be released to the elementary AppCenter. This is how it looks like:

![Time-Limit-Preview](https://user-images.githubusercontent.com/392542/73937710-f5fe0f00-48e5-11ea-9f57-9dd1b4a488f1.gif)

Thanks again for all your help and providing the design!!

**Comment by michaelvillar** [comment]
That looks great!

**Comment by karbassi** [comment]
Updated Sketch file with dark mode. 

[timer-app.sketch.zip](https://github.com/michaelvillar/timer-app/files/4464914/timer-app.sketch.zip)
