### ISSUE TITLE
Window without timer controls

### ISSUE THREAD

**Issue by Pandorin** [michaelvillar/timer-app#60]
**Steps to Reproduce:**
1. Clone rep;
2. Open project in Xcode (my Version 11.3.1 (11C504));
3. Build project (I just set up "Signing -> Development Team" in "Build Settings", fix or not swift warnings  - irrelevant);
4. Build success, but app without timer controls:
![timer_builded](https://user-images.githubusercontent.com/1074906/74599568-5125c380-5095-11ea-863c-7bffc3606c7e.png)

But installed from [brew](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/michaelvillar-timer.rb) (`brew cask install michaelvillar-timer`) works fine:
![image](https://user-images.githubusercontent.com/1074906/74599645-559eac00-5096-11ea-8ab4-e243a3e43c2f.png)

**Comment by karbassi** [comment]
Fixed in #50
