### ISSUE TITLE
No notification / no sound

### ISSUE THREAD

**Issue by AndyDeNike** [michaelvillar/timer-app#61]
Running macOS Catalina V10.15.3

**Comment by AndyDeNike** [comment]
Well I do get the bouncing clock (which is probably the notification?) but still no sound.

**Comment by robinstewart** [comment]
There should be a system notification with sound. This is what I get on macOS 10.14.6:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/15016520/75392566-27dd1280-58a1-11ea-9497-099bf9f1d419.png">

**Comment by AndyDeNike** [comment]
After adjusting System Preference -> Notifcations -> Timer and turning on all options (banner, sound etc) I am now recieving the notification in top right corner (as your screenshot indicates) but still no sound.

**Comment by thiagomgd** [comment]
No sound for me either.
Also, because it vanishes after a few seconds, I completely missed it while I was coding:
using editor full screen on external monitor, and notification shortly appeared n my laptop, which I wasn't paying attention

**Comment by robinstewart** [comment]
I'm still not running Catalina so I can't test this myself, but if any of you are able to build the app from source, can you try out my `volume-control` branch and let me know if the sound plays in Catalina? (You will have to build and run in Xcode.)

https://github.com/robinstewart/timer-app/tree/volume-control

I'm using a different sound API in this branch (`AVAudioPlayer`) — it may be that the previous API was removed in Catalina.

**Comment by robinstewart** [comment]
I've submitted an update with _only_ the AVAudioPlayer change: #80

**Comment by karbassi** [comment]
@AndyDeNike @thiagomgd Can you test out latest version (1.5.3) to verify the issue has been fixed?

**Comment by AndyDeNike** [comment]
@karbassi Fully functional on 1.5.3 !  Both notification and sound are now available on my current Catalina version 10.15.4
