### ISSUE TITLE
Buggy mouse control 

### ISSUE THREAD

**Issue by syimyuzya** [michaelvillar/timer-app#71]
**Describe the bug**
Hard (or even unable) to drag the blue triangle near diagonal positions.

**To Reproduce**
- Open a timer
- Set time to one of the following: 5 min (top-right), 20 min (bottom-right), 35 min (bottom-left) or 50 min (top-left)
- Try to drag the blue triangle again

**Expected behavior**
The blue triangle should be dragged.

**Actual behavior**
The whole window is dragged.

**Desktop (please complete the following information):**
 - OS version: macOS 10.14.6
 - Version 1.5.0

**Comment by luckman212** [comment]
I can reproduce this too, on 10.15.4

**Comment by karbassi** [comment]
Yup, I can reproduce as well.

@robinstewart do you think this has to do with the change in #40 (Changing `NSImageView` to `NSView`) ?

**Comment by karbassi** [comment]
Update, I reverted the changes in https://github.com/robinstewart/timer-app/commit/2fd3f8292355d936e209d34461b0a4d02aae2625 and the error went away. I wonder what part of the changes is the issue.

**Comment by karbassi** [comment]
Fixed. Thanks @syimyuzya and @luckman212 for reporting it.
