### ISSUE TITLE
remove the icon in dock

### ISSUE THREAD

**Issue by maxk77** [michaelvillar/timer-app#73]
**Describe the bug**
Right-click and uncheck the "show in dock" cannot remove the icon in dock. And if I quit and reopen the app, the "show in dock" menu item will be checked again, so It won't remember my decision. 

**Screenshots**
![Screen Shot 2020-04-12 at 13 04 51](https://user-images.githubusercontent.com/26541990/79061058-9eea3100-7cbe-11ea-8178-036faf3107d7.png)

**Desktop (please complete the following information):**
macOS 10.15.4
Version 1.5.1

**Additional context**
Am I doing it wrong?

**Comment by karbassi** [comment]
@max-yeah You didn't do anything wrong. The option is confusing.

"Show in Dock" should be renamed to "Show timer badge in Dock".

See https://github.com/michaelvillar/timer-app/pull/42

We should rename it to remove any future confusion.

**Comment by maxk77** [comment]
I see. Thank you.
