### ISSUE TITLE
keep on top

### ISSUE THREAD

**Issue by technovangelist** [michaelvillar/timer-app#78]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
I wish there was an option to keep the timer on top of all windows. I am using this in a presentation where I show instructions for a hands on lab and would love to also show how much time is left in the lab.

**Describe alternatives you've considered**
Ive looked at a lot of timers, but this is perfect because its so simple.

**Comment by robinstewart** [comment]
This feature already exists! 😄

**Window** menu -> **Stay on top**

**Comment by technovangelist** [comment]
Wow, look at that. there it is. doh!
