### ISSUE TITLE
Add logs

### ISSUE THREAD

**Issue by b0ttle** [michaelvillar/timer-app#83]
**Is your feature request related to a problem? Please describe.**
It is difficult for me to record every timer i set up when i focus on a task. 

**Describe the solution you'd like**
It can export logs for today or this week's timers status.

**Comment by karbassi** [comment]
@b0ttle Thanks for this amazing request. It seems like you want a Pomodoro timer. We're aiming to keep the app simple and single-task focused. Check out https://thesweetsetup.com/apps/best-pomodoro-app-mac-ios/ for some other apps that may help.
