### ISSUE TITLE
Use a fixed-width font and leading zeros for less jank

### ISSUE THREAD

**Issue by nvenegas** [michaelvillar/timer-app#85]
Hi

**Is your feature request related to a problem? Please describe.**
I notice little movements of the timer's contents—aka "jank"—out of the corner of my eye which is distracting

**Describe the solution you'd like**
* Use a fixed width font, please, so that, e.g., `51"` → `50"` doesn't move around
* Use leading zeroes, please, so that, e.g., `10"` → `9"` doesn't move around (it would be `10"` → `09"`)

**Describe alternatives you've considered**
Hiding the Timer window, but when screen sharing that would make it hard for all participants to be aware of our current interval

Cheers!

**Comment by karbassi** [comment]
I agree with this! I'll take a look at this.

**Comment by nvenegas** [comment]
@karbassi thanks for creating #86!

Not sure if y'all also agree with leading zeroes (top row without, bottom row with):
<img width="218" alt="no-zeroes-double-digits" src="https://user-images.githubusercontent.com/50625/86980417-1993f100-c1c7-11ea-8f58-9cd64da90f3f.png"> <img width="218" alt="no-zeroes-single-digit" src="https://user-images.githubusercontent.com/50625/86980420-1ac51e00-c1c7-11ea-9dd5-be2345f5049e.png">

<img width="262" alt="double-digits" src="https://user-images.githubusercontent.com/50625/86980240-b30ed300-c1c6-11ea-8502-dec0976d80e3.png"> <img width="262" alt="single-digits" src="https://user-images.githubusercontent.com/50625/86980243-b4400000-c1c6-11ea-88f2-c2bbe132f203.png">

If so, here's the patch
```diff
diff --git a/Timer/MVClockView.swift b/Timer/MVClockView.swift
index c372470..8c63fbf 100644
--- a/Timer/MVClockView.swift
+++ b/Timer/MVClockView.swift
@@ -310,10 +310,10 @@ class MVClockView: NSControl {
     var suffixWidth: CGFloat = 0
 
     if (self.seconds < 60) {
-      minutesLabel.string = NSString(format: "%i\"", Int(self.seconds)) as String
+      minutesLabel.string = NSString(format: "%02i\"", Int(self.seconds)) as String
       suffixWidth = minutesLabelSecondsSuffixWidth
     } else {
-      minutesLabel.string = NSString(format: "%i'", Int(self.minutes)) as String
+      minutesLabel.string = NSString(format: "%02i'", Int(self.minutes)) as String
       suffixWidth = minutesLabelSuffixWidth
     }
     minutesLabel.sizeToFit()
@@ -326,7 +326,7 @@ class MVClockView: NSControl {
       secondsLabel.string = ""
     }
     else {
-      secondsLabel.string = NSString(format: "%i\"", Int(self.seconds.truncatingRemainder(dividingBy: 60))) as String
+      secondsLabel.string = NSString(format: "%02i\"", Int(self.seconds.truncatingRemainder(dividingBy: 60))) as String
       secondsLabel.sizeToFit()
 
       frame = secondsLabel.frame
```

**Comment by karbassi** [comment]
@nicolasv I personally don't think the zero-pad looks good. The change in digits happens once (`10 minutes to 9 minutes`) or at most twice (`100 minutes to 99 minutes` and `10 minutes to 9 minutes`). To me, that's not that jarring.

Thoughts @michaelvillar @robinstewart?

**Comment by robinstewart** [comment]
I agree with @karbassi that the few times the number of digits changes is not worth adding the visual noise of a leading zero, by default. The clean visual design is an important part of what makes this app special.

But this would be a fine setting to go in the preferences for those like @nicolasv who want to turn it on.

**Comment by karbassi** [comment]
Zero-pad is related to #89

**Comment by nvenegas** [comment]
> But this would be a fine setting to go in the preferences for those like @nicolasv who want to turn it on.

Using the newly released version (with fixed-width font, but no zero padding) — and I really like it! So I'm no longer requesting zero padding :)

**Comment by robinstewart** [comment]
@nicolasv Awesome! 😄

**Comment by karbassi** [comment]
I'm glad! @nicolasv
