### ISSUE TITLE
Cannot run timer after using `brew cask install michaelvillar-timer` 

### ISSUE THREAD

**Issue by johngrant** [michaelvillar/timer-app#97]
## Describe the bug
MacOS security preventing timer from running after install via `brew cask install michaelvillar-timer`

## To Reproduce
1. Open Terminal
2. Run command `brew cask install michaelvillar-timer`
3. After install finishes hit CMD+Spacebar and type `timer` to bring up the timer app installed in step 2. Press enter.
4. A dialog appears preventing the app to run.

## Expected behavior
Timer app would start in a usable state.

## Screenshots

![Screenshot 2024-04-24 at 1 32 50 PM](https://github.com/michaelvillar/timer-app/assets/17738/2c3baaa0-b849-4909-854e-5e5018d5628c)

## Desktop (please complete the following information):
 - OS version: [e.g. macOS 10.15.4]

**Comment by karbassi** [comment]
[Safely open apps on your Mac](https://support.apple.com/en-us/HT202491)

**Comment by johngrant** [comment]
@karbassi Thanks, that helps! I was looking for similar instructions yesterday, but why can't the app be signed to prevent the warning?

**Comment by luckman212** [comment]
@johngrant are you volunteering to pay the $99 yearly Apple Developer fee? 😉

**Comment by johngrant** [comment]
> @johngrant are you volunteering to pay the $99 yearly Apple Developer fee? 😉

No thanks! The instructions from Apple helped run the app without the warning. I like it and it makes a great Pomodoro or time box timer, but $99 is a bit too steep right now. Damn closed Apple eco-system. I would donate a little less than that though.
