### ISSUE TITLE
The app fails to start on macOS Catalina

### ISSUE THREAD

**Issue by glebignatieff** [michaelvillar/timer-app#99]
**Describe the bug**
The app isn't signed or notarized thus it fails to start.

**To Reproduce**
1. Download the app using the link in the description or using `brew cask`.
2. Run the app.

**Expected behavior**
Start up successfully.

**Screenshots**
<img width="532" alt="image" src="https://user-images.githubusercontent.com/5960869/93670954-bf0cf000-faa7-11ea-86e7-08e60e945202.png">

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.6

**Comment by wize-wiz** [comment]
@glebignatieff Start a fund for the dev-op to pay the fees so it will startup as expected ..

**Comment by glebignatieff** [comment]
> @glebignatieff Start a fund for the dev-op to pay the fees so it will startup as aspected ..

I might be wrong, but this app is macOS-only and Catalina holds more than a half of the market share, so I'm a bit confused.

**Comment by robinstewart** [comment]
@glebignatieff Notarization requires a paid Apple Developer account ($99/yr) so I think @wize-wiz suggestion was to fund such an account.

**Comment by karbassi** [comment]
[Safely open apps on your Mac](https://support.apple.com/en-us/HT202491)

Duplicate of #97
